### ISSUE TITLE
Error: unknown flag: --name

### ISSUE THREAD

**Issue by aradwyr** [gremlin/helm#12]
When trying to add Helm to my cluster:

$ helm install gremlin/gremlin \
\--namespace gremlin \
\--name gremlin \
\--set gremlin.teamID=$GREMLIN_TEAM_ID \
\--set gremlin.clusterID=$GREMLIN_CLUSTER_ID

Returned: 
Error: unknown flag: --name

I tried leaving --name off entirely: 
$ helm install gremlin/gremlin \
 \--namespace gremlin \
 \--set gremlin.teamID=$GREMLIN_TEAM_ID \
 \--set gremlin.clusterID=$GREMLIN_CLUSTER_ID

Returned:
Error: must either provide a name or specify --generate-name

Using --generate-name did work though:
`$ helm install gremlin/gremlin \--namespace gremlin \--generate-name \--set gremlin.teamID=$GREMLIN_TEAM_ID \--set gremlin.clusterID=$GREMLIN_CLUSTER_ID`

**Comment by mlafeldt** [comment]
@sbd It should be `helm install gremlin gremlin/gremlin` without `--name`.

In fact, it's even better to use `helm upgrade gremlin gremlin/gremlin --install`, which allows installing *and* upgrading the chart, no matter if it's already installed or not.

**Comment by kiich** [comment]
the use `--name` seems to be removed from helm 3 - i also ran into this error when I upgraded my local helm.

fixed by using ```helm install gremlin gremlin/gremlin --namespace gremlin --set gremlin.teamID=$GREMLIN_TEAM_ID --set gremlin.clusterID=$GREMLIN_CLUSTER_ID```

**Comment by sbd** [comment]
I was following commands listed in this tutorial: https://www.gremlin.com/community/tutorials/how-to-install-and-use-gremlin-with-eks/

**Comment by kiich** [comment]
Yep, it looks like it's the same content as https://www.gremlin.com/docs/infrastructure-layer/installation/#helm which is where I also followed and ran into the same error as you.

I think this helm 3 change should be clearer in the doc in my view.

**Comment by dpappa** [comment]
Yep! I think the readme just needs to be updated with helm3 support. 
Tammy wrote some great directions which take into account what helm version is being used: https://www.gremlin.com/community/tutorials/how-to-install-and-use-gremlin-with-kubernetes/

**Comment by philgebhardt** [comment]
Thanks everyone. I've removed the references to helm2 arguments in the README. Looks like our documentation at the following url should also be updated.

https://www.gremlin.com/docs/infrastructure-layer/installation/#helm
