### ISSUE TITLE
Can't define nodeSelector for chao-deployment template

### ISSUE THREAD

**Issue by apavarnitsyn** [gremlin/helm#30]
Right now nodeSelector and other affinity rules from default values file are used only for gremlin daemonSet installation.
But it'll be great also to define these parameters for chao-deployment.
Right now I see three ways to do that:
1) use the same value `nodeSelector: {}` from values.yaml inside of  chao-deployment for backward compatibility;
2) copy `affinity: {}` , `tolerations: []` , and `nodeSelector: {}` inside of `chaoimage: ...`
3) move these lines also into `image: ...`. In this case Gremlin deamonSet and chao Deployment will be defined the same way.
I'd like to discuss the way it would be better to fix.

**Comment by gremsam** [comment]
I believe this was resolved with: https://github.com/gremlin/helm/pull/57

Let us know if you still have problems
