### ISSUE TITLE
add: please support multi-arch(including ARM64) Docker image

### ISSUE THREAD

**Issue by Stdev17** [gremlin/helm#38]
Hello, I've found that CrashLoopBackOff error occurs when I am installing Gremlin service on an EKS cluster. Through further investigation, the problem might seem to happen only on ARM64 VMs. I had added an x86_64 VM pool and it works fine on that VMs. However, I could not find an image supporting ARM64 in the Docker hub. Inspecting the manifest of the image, I ended up finding there is no arch setting for ARM64 but x86_64. There are increasing demands on various VM architectures for various modern workloads. I hope your product will be capable of satisfying these needs soon.

**Comment by SchillyVanilly** [comment]
@Stdev17 Hello! I'm a Product Manager at Gremlin. Thank you for this product insight. We currently don't support ARM64 but I added this to our ProductBoard insight board to capture the request. I'm going to email you to ask some details about this request. Thank you.

**Comment by thefirstofthe300** [comment]
ARM64 is now supported. You can find the appropriate tags in our Docker Hub repo.

https://hub.docker.com/r/gremlin/gremlin/tags
