### ISSUE TITLE
Custom certificate authority does not work for chao deployment

### ISSUE THREAD

**Issue by cknowles** [gremlin/helm#42]
Using `ssl.certFile` correctly injects into the trusted certificate authorities for the `gremlin` Daemon Set but not the `chao` Deployment. To reproduce set `ssl.certFile` and then look inside the 

I believe it's due to the conditional for `certFile` being inside the conditional for `gremlin.secretType` rather than separate.
https://github.com/gremlin/helm/blob/e6f04a94fed4a9ebec7a3a3d1efed408544202bf/gremlin/templates/chao-deployment.yaml#L85-L104

A example use case where this would be needed is any corporate environment where there are egress controls like Zscaler, Netskope etc.

**Comment by philgebhardt** [comment]
Thanks for filing an issue @cknowles. I agree with your assessment. Fix is likely to refactor the `volumes` and `volumeMounts` sections so that we set the appropriate configuration regardless of `secretType`.

**Comment by philgebhardt** [comment]
This is now available in helm chart `0.3.1` (#44)
